import type { Metadata } from "next";

import { LegalShell, Section } from "@/components/legal/legal";

export const metadata: Metadata = {
  title: "Privacy Policy — Build & Launch AI",
  description: "How Build & Launch AI collects, uses, and protects your data.",
};

export default function PrivacyPage() {
  return (
    <LegalShell title="Privacy Policy" updated="July 24, 2026">
      <Section title="What we collect">
        <ul>
          <li>
            <strong>Account info:</strong> name, email, and authentication data
            when you sign up.
          </li>
          <li>
            <strong>Billing info:</strong> handled entirely by Paddle, our merchant
            of record &mdash; we receive confirmation of your subscription status
            but never your card details.
          </li>
          <li>
            <strong>API keys:</strong> if you use BYOK tools, your third-party API
            keys are encrypted (AES-256-GCM) and stored to let you run tools
            without re-entering them each time.
          </li>
          <li>
            <strong>Usage data:</strong> which tools you run and when, so you can
            see your run history.
          </li>
          <li>
            <strong>Run artifacts:</strong> outputs generated by tools you run,
            retained for 30 days.
          </li>
        </ul>
      </Section>

      <Section title="How we use it">
        <ul>
          <li>
            To provide and operate the platform (running tools, managing your
            membership).
          </li>
          <li>
            To communicate with you about your account, billing, or changes to our
            service.
          </li>
        </ul>
      </Section>

      <Section title="Who we share it with (sub-processors)">
        <ul>
          <li>
            <strong>Paddle</strong> &mdash; payment processing and billing (Paddle
            is merchant of record)
          </li>
          <li>
            <strong>Supabase</strong> &mdash; database and authentication
          </li>
          <li>
            <strong>Vercel</strong> &mdash; application hosting
          </li>
          <li>
            <strong>Cloudflare R2</strong> &mdash; file/artifact storage
          </li>
          <li>
            <strong>Resend</strong> &mdash; transactional email delivery
          </li>
          <li>
            <strong>AI providers you connect</strong> &mdash; only when you run a
            tool using your own key; we don&rsquo;t share your key or data with
            providers you haven&rsquo;t connected
          </li>
        </ul>
        <p>We do not sell your data.</p>
      </Section>

      <Section title="Data retention">
        <ul>
          <li>Run artifacts: 30 days, then automatically deleted.</li>
          <li>
            Account data: retained while your account is active, and for 30 days
            after cancellation/deletion, then removed.
          </li>
          <li>
            API keys: deleted immediately if you remove them from your account or
            delete your account.
          </li>
        </ul>
      </Section>

      <Section title="Your rights">
        <p>
          You can request a copy of your data, ask us to correct it, or ask us to
          delete your account and associated data by contacting{" "}
          <a href="mailto:support@buildnlaunchai.com">
            support@buildnlaunchai.com
          </a>
          .
        </p>
      </Section>

      <Section title="International users">
        <p>
          If you&rsquo;re outside Bangladesh, your data may be processed by our
          sub-processors in other countries (e.g., US-based Supabase/Vercel
          infrastructure). By using Build &amp; Launch AI, you consent to this
          transfer.
        </p>
      </Section>

      <Section title="Changes to this policy">
        <p>
          We&rsquo;ll update this page and notify you of material changes via email
          or a site notice.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Privacy questions?{" "}
          <a href="mailto:support@buildnlaunchai.com">
            support@buildnlaunchai.com
          </a>
        </p>
      </Section>
    </LegalShell>
  );
}
