import type { Metadata } from "next";

import Link from "next/link";

import { LegalShell, Section } from "@/components/legal/legal";

export const metadata: Metadata = {
  title: "Privacy Policy — Build & Launch AI",
  description: "How Build & Launch AI collects, uses, and protects your data.",
};

export default function PrivacyPage() {
  return (
    <LegalShell title="Privacy Policy" updated="August 28, 2026">
      <Section title="What we collect">
        <ul>
          <li>
            <strong>Account info:</strong> name, email, and authentication data
            when you sign up.
          </li>
          <li>
            <strong>Billing info:</strong> handled entirely by Creem, our merchant
            of record &mdash; we receive confirmation of your subscription status
            but never your card details.
          </li>
          <li>
            <strong>API keys:</strong> if you use BYOK tools, your third-party API
            keys are encrypted (AES-256-GCM) and stored to let you run tools
            without re-entering them each time.
          </li>
          <li>
            <strong>Usage data:</strong> which tools you run and when, so you can
            see your run history.
          </li>
          <li>
            <strong>Run artifacts:</strong> outputs generated by tools you run,
            retained for 30 days.
          </li>
          <li>
            <strong>Credit records:</strong> if you buy credits, we keep your
            balance and a line for every credit that moves \u2014 when, which app,
            which provider and model, and what it cost. Deliberately not the
            content: the ledger records that a call happened and what it was
            billed at, never what you sent or what came back.
          </li>
        </ul>
      </Section>

      <Section title="How we use it">
        <ul>
          <li>
            To provide and operate the platform (running tools, managing your
            membership).
          </li>
          <li>
            To communicate with you about your account, billing, or changes to our
            service.
          </li>
        </ul>
      </Section>

      <Section title="Who we share it with (sub-processors)">
        <ul>
          <li>
            <strong>Creem</strong> &mdash; payment processing and billing (Creem
            is merchant of record)
          </li>
          <li>
            <strong>Supabase</strong> &mdash; database and authentication
          </li>
          <li>
            <strong>Vercel</strong> &mdash; application hosting
          </li>
          <li>
            <strong>Cloudflare R2</strong> &mdash; file/artifact storage
          </li>
          <li>
            <strong>Resend</strong> &mdash; transactional email delivery
          </li>
          <li>
            <strong>AI providers you connect</strong> &mdash; only when you run a
            tool using your own key; we don&rsquo;t share your key or data with
            providers you haven&rsquo;t connected
          </li>
          <li>
            <strong>OpenAI</strong> and <strong>ElevenLabs</strong> &mdash;{" "}
            <strong>only when you run on credits.</strong> See below.
          </li>
        </ul>
        <p>We do not sell your data.</p>
      </Section>

      {/* ─── THE CHANGE CREDIT MODE MADE ───────────────────────────────────
          On BYOK, the AI provider is YOUR processor: your key, your account,
          your contract with them, and our only role is holding the encrypted
          key. On credits the request leaves our account, which makes those
          providers OUR sub-processors for that call \u2014 a different legal
          relationship, not a different vendor. Listing them without saying that
          would be a list that is technically complete and materially
          misleading. */}
      <Section title="AI providers, and what changes on credits">
        <p>
          <strong>When you run on your own key</strong>, the request goes to a
          provider you chose, on your account, under your agreement with them. We
          store your key encrypted and never see the plaintext; what that
          provider does with your data is between you and them.
        </p>
        <p>
          <strong>When you run on credits</strong>, the request is made on our
          provider accounts instead. Those providers become our sub-processors
          for that call, and whatever you send \u2014 your prompt, and any file or
          URL the tool passes on \u2014 is processed by them under their own terms
          and their own retention policies, which we do not control. Today those
          providers are <strong>OpenAI</strong> (text) and{" "}
          <strong>ElevenLabs</strong> (speech). If that list changes, this page
          changes with it.
        </p>
        <p>
          Which mode you are in is never a surprise: it is shown before you run
          anything, and on your <Link href="/dashboard/credits">credits page</Link>.
        </p>
      </Section>

      <Section title="Data retention">
        <ul>
          <li>Run artifacts: 30 days, then automatically deleted.</li>
          <li>
            Account data: retained while your account is active, and for 30 days
            after cancellation/deletion, then removed.
          </li>
          <li>
            API keys: deleted immediately if you remove them from your account or
            delete your account.
          </li>
          <li>
            Credit records: kept for as long as the account exists, and deleted
            with it. They are append-only while it does \u2014 an entry is never
            edited or removed, because it is the only thing that can answer
            &ldquo;where did my credit go&rdquo;.
          </li>
        </ul>
      </Section>

      <Section title="Your rights">
        <p>
          You can request a copy of your data, ask us to correct it, or ask us to
          delete your account and associated data by contacting{" "}
          <a href="mailto:support@buildnlaunchai.com">
            support@buildnlaunchai.com
          </a>
          .
        </p>
      </Section>

      <Section title="International users">
        <p>
          If you&rsquo;re outside Bangladesh, your data may be processed by our
          sub-processors in other countries (e.g., US-based Supabase/Vercel
          infrastructure). By using Build &amp; Launch AI, you consent to this
          transfer.
        </p>
      </Section>

      <Section title="Changes to this policy">
        <p>
          We&rsquo;ll update this page and notify you of material changes via email
          or a site notice.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Privacy questions?{" "}
          <a href="mailto:support@buildnlaunchai.com">
            support@buildnlaunchai.com
          </a>
        </p>
      </Section>
    </LegalShell>
  );
}
